name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login se4453acr.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t se4453acr.azurecr.io/se4453app:latest .

      - name: Push Docker Image
        run: |
          docker push se4453acr.azurecr.io/se4453app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: se4453app-container
          images: se4453acr.azurecr.io/se4453app:latest
